CREATE TABLE raiting
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value    INTEGER                                 NOT NULL,
    movie_id BIGINT,
    CONSTRAINT pk_raiting PRIMARY KEY (id)
);

ALTER TABLE raiting
    ADD CONSTRAINT FK_RAITING_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movie (id);